// 手册内容 A：第 1–18 章（全部事实来自仓库真实代码，v27 终态）
module.exports = [
{ h1: "第 1 章 项目概述" },
{ p: "供需透镜（SupplyLens）是面向工业园区与制造企业的再生材料供需匹配和净减排决策系统。它把园区内外的再生材料供给批次与企业的替代需求连接起来，在规格、数量、时窗、价格、运输等硬约束下给出可落地的匹配与组合方案，并计算净减排量与绿色成本，每个数字可逐项展开手算。" },
{ p: "项目类型为本地离线 Web 应用（Python 标准库实现，无外部服务依赖）。主要用户：园区运营方、产废/供料企业、用料企业采购与工艺人员。核心业务链路：创建替代任务 → 录入/导入供给批次 → 证据补全 → 引擎计算（门槛分流、组合前沿、N-1 压测、敏感性）→ 方案比较 → 确认预留 → 履约反馈 → 决策护照；另有多需求撮合（只读建议）与建议单导出。" },
{ p: "当前完成度（v27，2026-09-18）：功能完整可用，自动化测试 271/271 全绿（零跳过），独立穷举核验 47/47，四套真实 Chrome E2E 共 75 项断言全绿，发行核验 14/14，演示自检 9/9。整体架构分三层：静态演示层（run.py 生成报告/仪表盘/评委网站）、试点工作台（pilot/，SQLite 多用户 Web 应用）、引擎层（src/，确定性算法，被上两层共用）。" },

{ h1: "第 2 章 技术栈" },
{ p: "下表为项目真实技术栈。本项目刻意保持零框架、零外部运行依赖（除 PyYAML），不使用 Redis、消息队列、Docker、第三方 API 与 AI 服务。" },
{ tbl: { head: ["类别", "技术", "实际版本/说明", "作用"], w: [14, 30, 26, 30], rows: [
  ["前端", "原生 HTML/CSS/JS", "无框架、无构建、无 CDN", "评委网站（site/index.html）与工作台（pilot/static/）"],
  ["后端", "Python 标准库 http.server", "Python ≥ 3.12", "试点工作台服务（pilot/server.py）与演示站（serve.py）"],
  ["数据库", "SQLite（stdlib sqlite3）", "单文件 pilot/data/pilot.sqlite3", "工作台全部业务数据；自动建表与版本迁移"],
  ["ORM", "无", "手写参数化 SQL", "pilot/db.py 统一封装"],
  ["引擎加速", "OR-Tools CP-SAT", "≥9.0，可选", "组合超限时的精确完整前沿；缺失时自动回退贪心（已知差异）"],
  ["模板/序列化", "PyYAML", "≥6.0（唯一必装第三方）", "因子表/行业配置/证据动作 YAML 读取"],
  ["测试", "pytest + Playwright + requests", "开发依赖", "271 项单测/集成；四套真实 Chrome E2E"],
  ["构建", "无构建步骤", "—", "前端直接托管静态文件；Python 直接运行"],
  ["部署", "本机/局域网", "可选 systemd（见 Linux 部署指南）", "绑定 127.0.0.1 或内网网卡，建议置于反向代理之后"],
]} },
{ p: "必装：Python 3.12+、PyYAML。可选：ortools（不装则引擎超限场景走贪心回退，Windows 侧即为该口径，属已知差异）。仅开发需要：pytest、playwright、requests、Git。运行期不存在 Redis、消息队列、对象存储、邮件、支付等外部服务；数据全程不出本机。" },

{ h1: "第 3 章 项目目录结构" },
{ code: "供需透镜-绿创赛/\n├─ run.py               # 演示层入口：生成报告/仪表盘/评委网站\n├─ serve.py             # 演示站静态服务（127.0.0.1，白名单目录）\n├─ src/                 # 引擎层（确定性算法，全部业务计算在这里）\n│   ├─ material.py      #   硬门槛/组合前沿/N-1/敏感性/并行化（核心）\n│   ├─ ledger.py        #   净减排账本与绿色成本\n│   ├─ matching.py      #   多需求撮合引擎（Gale-Shapley 容量变体）\n│   ├─ matching_sheet.py#   撮合建议单 HTML 渲染\n│   ├─ material_match.py#   名称标准化与召回\n│   ├─ evidence_value.py/ evidence_quality.py  # 证据价值/质量\n│   ├─ passport.py      #   决策护照（Schema v2）\n│   ├─ visuals.py       #   零依赖内联 SVG 图表\n│   ├─ report.py / dashboard.py / site_builder.py  # 三类产物渲染\n│   ├─ imports.py / validation.py  # CSV 体检 / 唯一领域校验层\n│   └─ greedy_baseline.py / scenarios.py / feedback.py / config.py / main.py\n├─ pilot/               # 试点工作台\n│   ├─ server.py        #   HTTP 路由与全部 API（核心）\n│   ├─ auth.py          #   口令哈希/会话/CSRF/口令策略\n│   ├─ db.py            #   SQLite 连接/事务/迁移\n│   ├─ api.py           #   请求体 → 领域对象（共用校验层）\n│   ├─ start_pilot.py   #   启动入口\n│   ├─ init_admin.py    #   CLI 建管理员\n│   ├─ import_sample.py / backup_restore.py\n│   └─ static/          #   workbench.html + app.js + style.css\n├─ config/              # 因子表/行业配置/证据动作（YAML）\n├─ templates/           # 供给/需求/反馈 CSV 模板\n├─ schemas/             # 决策护照 JSON Schema（v1/v2）\n├─ tests/               # 271 项测试 + 四套 E2E（e2e_*.py）\n├─ benchmarks/          # 基准/压测脚本与原始实测数据\n├─ scripts/             # 发行构建/验证/自检/截图/影子试算\n├─ docs/                # 全部文档（地图见 docs/INDEX.md）\n├─ dist/                # 发行双包（构建产物，不入 git）\n├─ output/ site/        # 演示层生成产物\n└─ 清华绿创赛/          # 用户个人暂存区（勿动）" },
{ tbl: { head: ["路径", "作用", "什么情况下修改"], w: [30, 38, 32], rows: [
  ["src/material.py", "门槛/组合前沿/N-1/敏感性", "改匹配或计算逻辑（改动须逐位一致验证）"],
  ["src/ledger.py", "净减排与成本账本", "改核算口径（需与因子表约定一致）"],
  ["pilot/server.py", "全部 HTTP API", "新增/修改接口、鉴权、安全头"],
  ["pilot/static/app.js", "工作台全部交互与渲染", "改页面行为、表格、表单"],
  ["pilot/static/style.css", "工作台样式（亮/暗主题）", "纯视觉调整"],
  ["config/material_emission_factors.yaml", "排放因子与核算约定", "接入真实因子（需建新基准版本）"],
  ["tests/", "自动化回归", "每次改动后运行；新增能力补测试"],
  ["scripts/build_release.py", "发行白名单", "新增交付文件时登记"],
  ["CHANGELOG.md", "逐轮变更记录", "每次用户可见变更"],
]} },

{ h1: "第 4 章 系统整体运行原理" },
{ p: "项目包含两类运行形态。形态一（静态演示层）：run.py 读取 YAML 配置与内置演示数据，调用 src/ 引擎计算后，把结果渲染为 Markdown/HTML 报告、离线仪表盘与评委网站；serve.py 仅负责把 site/ 与 output/ 以静态方式托管在 127.0.0.1:8765，无任何动态逻辑。" },
{ p: "形态二（试点工作台，本项目主体）：浏览器打开 http://127.0.0.1:8765/ 后，由 pilot/server.py 返回 pilot/static/workbench.html，随后 app.js 接管全部交互。真实请求流程如下：" },
{ code: "用户操作（工作台页面）\n ↓\npilot/static/app.js（视图渲染 + fetch 调用）\n ↓\nHTTP JSON API（/api/...，Cookie 会话 + CSRF 头）\n ↓\npilot/server.py（do_GET/do_POST 路由分支 → _api_* 处理器）\n ↓\npilot/api.py（请求体 → 领域对象，经 src/validation.py 校验）\n ↓\nsrc/material.py 等引擎计算 / pilot/db.py 参数化 SQL\n ↓\nSQLite（pilot/data/pilot.sqlite3）\n ↓\n_json() 返回 JSON（附安全响应头）\n ↓\napp.js 更新状态并重渲染对应视图" },
{ p: "要点：前端无独立服务与构建；app.js 以单页多视图（view-* 区块）方式组织；所有写接口要求会话 Cookie + X-CSRF-Token 双校验，服务端按角色鉴权；异步大任务通过 runs?async=1 受理 + 轮询 /api/runs/jobs/{id} 实现。" },

{ h1: "第 5 章 开发环境安装" },
{ p: "第一次拿到项目需要安装的软件（仅此而已，不需要 Node、Java、MySQL、Redis、Docker）：" },
{ tbl: { head: ["软件", "用途", "推荐版本", "必装"], w: [22, 40, 20, 18], rows: [
  ["Git", "获取代码", "任意较新版本", "建议"],
  ["Python", "运行全部代码", "3.12 及以上（3.14 已实测）", "必装"],
  ["VS Code / PyCharm", "编辑与调试", "任意", "任选其一"],
  ["Google Chrome", "四套 E2E 使用的真实浏览器", "较新版本", "仅开发"],
]} },
{ p: "可选组件：OR-Tools（pip 包 ortools，加速大组合场景；测试与演示不强制）。注意：若使用仓库自带的 Windows .e2e-venv 跑 E2E，该环境刻意不含 ortools，引擎超限场景走贪心回退，属已知且接受的差异，勿在其内补装后宣称一致。" },

{ h1: "第 6 章 第一次运行项目" },
{ pin: "第一步：获取代码" },
{ code: "git clone <项目地址>\ncd 供需透镜-绿创赛\n# 若已有本地目录，直接 cd 进入仓库根目录即可" },
{ pin: "第二步：检查环境" },
{ code: "python --version        # 期望 3.12 及以上（3.14 已实测通过）" },
{ pin: "第三步：安装依赖（建议虚拟环境）" },
{ code: "python -m venv .venv\n# Windows：\n.venv\\Scripts\\activate\n# macOS/Linux：\nsource .venv/bin/activate\n\npip install -r requirements.txt        # PyYAML（必装）\npip install ortools                    # 可选：大组合精确前沿加速" },
{ p: "验证安装：python -c \"import yaml\" 不报错即可。开发测试另需 pip install pytest requests playwright 及 Chrome（见第 30 章）。" },

{ h1: "第 7 章 环境变量配置" },
{ p: "项目没有 .env 文件，运行不依赖任何必填环境变量；全部业务配置在 config/ 目录的 YAML 中。代码中仅读取以下两个可选环境变量：" },
{ tbl: { head: ["变量名", "作用", "是否必填", "示例值", "使用位置"], w: [30, 34, 12, 10, 14], rows: [
  ["SUPPLYLENS_PARALLEL_WORKERS", "覆盖并行化线程数（0=自动）", "否", "1（强制串行）", "src/material.py"],
  ["MATERIAL_SOLVER_DEBUG", "输出求解器调试信息", "否", "1", "src/material.py"],
]} },

{ h1: "第 8 章 数据库准备" },
{ p: "数据库为 SQLite 单文件，无需安装任何数据库服务。位置：pilot/data/pilot.sqlite3（可用 start_pilot.py --db 换路径）。首次启动服务后，pilot/db.py 自动建齐全部表并把 schema 版本迁移到当前版本（v5），历史库自动逐版本迁移，无需手工执行 SQL。无 seed；演示数据通过界面或 pilot/import_sample.py 导入。" },
{ tbl: { head: ["动作", "方式"], w: [30, 70], rows: [
  ["创建/初始化", "启动 start_pilot.py 自动完成（幂等迁移）"],
  ["确认连接正常", "GET /api/health 返回 status=ok 且 users_exist 为 true/false 即读库成功"],
  ["备份", "工作台管理页「创建备份」（或 POST /api/backup），产物含 SHA-256 清单"],
  ["恢复", "管理页「恢复最近备份」（POST /api/backups/{name}/restore），恢复前自动 WAL checkpoint"],
  ["CLI 建管理员", "python pilot/init_admin.py --username admin --password <≥8位含字母数字>"],
]} },

{ h1: "第 9 章 启动项目" },
{ pin: "启动试点工作台（主体应用）" },
{ code: "python pilot\\start_pilot.py --port 8765      # Windows\npython pilot/start_pilot.py --port 8765      # macOS/Linux\n# 或双击 启动试点工作台.bat" },
{ p: "启动成功的表现：控制台打印服务启动信息且无异常栈；浏览器打开 http://127.0.0.1:8765/ 看到登录页。首次访问页面会要求初始化管理员（无默认密码，至少 8 位且含字母与数字）。API Base URL 即 http://127.0.0.1:8765（前端与接口同源，无跨域）。" },
{ pin: "启动静态演示网站（可选）" },
{ code: "python -B run.py --industry 再生PP --data-mode demo   # 生成 output/ 与 site/\npython -B serve.py --port 8765                        # 托管演示站\n# 或双击 启动演示网站.bat / 打开最新报告.bat" },
{ p: "前端不需要单独启动：工作台的 HTML/CSS/JS 由工作台服务直接托管。" },

{ h1: "第 10 章 如何关闭项目" },
{ p: "在服务所在终端按 Ctrl + C 即可停止工作台或演示站；SQLite 为嵌入式单文件，停止即安全落盘，无其它需要关闭的服务。若使用系统服务方式部署（systemd），用对应的 systemctl stop 命令。端口被占用时的处理见第 29 章。" },

{ h1: "第 11 章 如何确认项目运行成功" },
{ code: "□ 控制台无异常栈，服务监听 8765\n□ 打开 http://127.0.0.1:8765/ 显示登录页\n□ GET /api/health 返回 status=ok\n□ 初始化管理员或登录成功，进入任务列表\n□ 新建任务 → 录供给 → 运行计算 全链路可走通\n□ 浏览器 Console 无严重错误\n□ Network 无异常 500\n□（演示层）run.py 生成 output/ 三类产物且 site/index.html 可打开" },

{ h1: "第 12 章 项目功能总览" },
{ tbl: { head: ["功能", "用户入口", "前端代码", "后端代码", "API", "数据库"], w: [18, 16, 18, 18, 16, 14], rows: [
  ["登录/角色", "登录页", "app.js 视图 auth", "server.py auth 路由", "/api/auth/*", "users/sessions"],
  ["任务管理", "任务列表", "app.js view-tasks", "server.py tasks 路由", "/api/tasks*", "tasks"],
  ["供给/CSV 导入", "任务详情·供需", "app.js view-supplies", "supplies 路由", "/api/tasks/*/supplies*", "supplies/batches"],
  ["证据任务/版本", "任务详情·候选与证据", "app.js evidence 区块", "evidence 路由", "/api/tasks/*/evidence-*", "evidence_tasks/versions"],
  ["引擎运行/方案比较", "任务详情·方案比较", "app.js compare 区块", "runs 路由 + src/material.py", "/api/tasks/*/runs", "runs"],
  ["确认预留", "任务详情·方案比较", "app.js confirm 区块", "confirm/reservations 路由", "/api/tasks/*/confirm 等", "selections/reservations"],
  ["履约反馈", "任务详情·反馈", "app.js feedback 区块", "feedback 路由", "/api/tasks/*/feedback", "feedback"],
  ["决策护照", "任务详情·护照", "app.js passport 区块", "passport 路由 + src/passport.py", "/api/tasks/*/passport", "runs(快照)"],
  ["多需求撮合/建议单", "多需求撮合页", "app.js view-matching", "matching 路由 + src/matching*.py", "/api/matching/*", "只读试算，不落库"],
  ["用户/备份/审计", "管理卡片（管理员）", "app.js admin 区块", "users/backup/audit 路由", "/api/users|backup|audit", "users/audit_log"],
]} },

{ h1: "第 13 章 每个功能的详细说明" },
{ h2: "13.1 功能：登录与角色" },
{ p: "作用：多用户隔离与权限分级（admin 管理、editor 全业务、viewer 只读）。操作：打开首页 → 输入用户名密码 → 登录；首次启动先初始化管理员。成功：进入任务列表，右上出现用户徽章。常见失败：密码错误 401；连续失败触发 429 限流（900 秒内 10 次）；弱口令初始化返回 400（需含字母与数字）。" },
{ tbl: { head: ["层级", "位置"], w: [22, 78], rows: [
  ["前端入口", "pilot/static/workbench.html（view-auth）+ app.js 登录提交"],
  ["后端入口", "pilot/server.py 路由 auth/init|login|me|logout → _api_login 等"],
  ["认证逻辑", "pilot/auth.py（pbkdf2 20 万轮、secrets 令牌、compare_digest 恒时比较）"],
  ["数据库", "users（凭据/角色）、sessions（令牌/CSRF/过期时间）"],
  ["API", "POST /api/auth/login：请求 {username,password}；响应 Set-Cookie pilot_session（HttpOnly SameSite=Strict，HTTPS 反代自动加 Secure）+ {ok,csrf,username,role}"],
]} },
{ code: "app.js 登录提交\n ↓\nPOST /api/auth/login\n ↓\nserver.py _api_login（限流检查 → 查 users → pbkdf2 校验）\n ↓\n写 sessions 表 + Set-Cookie\n ↓\napp.js 保存 csrf → 切换到任务视图" },
{ h2: "13.2 功能：任务与供给（含 CSV 导入）" },
{ p: "作用：登记一条替代需求并挂接多个候选供给批次。操作：新建替代任务（向导填规格/数量/时窗）→ 任务详情「供需与质量」页手工录入或下载模板填好后 CSV 导入 → 系统做行级体检并返回结构化错误。成功：供给列表出现批次，批次可用量进入全局池。失败：缺必填列/数值非法会在响应 details 中逐行列出（400）。" },
{ p: "涉及文件：前端 app.js（view-tasks/view-supplies 与导入弹层）；后端 server.py supplies 路由 → pilot/api.py（demand_from_wizard/supply_from_payload）→ src/imports.py（CSV 体检）→ src/validation.py（领域校验）→ pilot/db.py 写 supplies/batches 表。" },
{ h2: "13.3 功能：运行引擎与方案比较" },
{ p: "作用：对任务执行确定性计算，产出可行组合的完整 Pareto 前沿、净减排账本、N-1 压测与敏感性核查。操作：方案比较页点「运行计算」（供给 ≥16 自动转后台异步并轮询进度）→ 完成后表格/散点图/账本可交互，支持保守/乐观口径切换与悬停联动。失败：因子缺失输出待补证据；候选供给超限且无 ortools 时回退贪心（结果标注）；401 会话过期自动回登录页。" },
{ code: "app.js 运行计算\n ↓\nPOST /api/tasks/{id}/runs（?async=1 受理返回 202+job_id）\n ↓\nserver.py _api_run_engine → 冻结输入快照（因子内容+SHA256 入 runs 表）\n ↓\nsrc/material.py：召回 → 三态硬门槛 → 组合枚举/CP-SAT 前沿 → N-1 → 敏感性\n ↓\nserialize_result → runs 表落库\n ↓\nGET /api/tasks/{id}/passport 或前端直接读运行结果渲染" },
{ h2: "13.4 功能：确认采购与预留" },
{ p: "作用：把选定方案落为库存事实（防超卖）。操作：比较页选定方案 → 填确认理由 → 确认；预留可 confirm/release/cancel 状态流转。失败：服务端新鲜度校验不通过（数据已变化）会拒绝并提示重算。" },
{ h2: "13.5 功能：多需求撮合与建议单" },
{ p: "作用：跨任务的全局稳定匹配建议（只读试算，不落库、不产生预留）。操作：任务列表 → 多需求撮合 → 勾选 ≥2 任务 → 计算 → 查看匹配明细/未满足原因/剩余容量/双边关系图 → 可导出打印友好 HTML 建议单。文件链：app.js view-matching → POST /api/matching/preview|sheet → src/matching.py → matching_sheet.py 渲染。" },
{ h2: "13.6 功能：决策护照" },
{ p: "作用：把选定运行冻结为可复核的 JSON 护照（绑定输入快照哈希与算法版本）。操作：护照页下载 JSON。文件链：app.js → GET /api/tasks/{id}/passport → src/passport.py（Schema v2）。" },

{ h1: "第 14 章 API 接口说明" },
{ p: "全部接口同源前缀 /api，返回 JSON；除标注公开者外均需会话 Cookie，写接口另需 X-CSRF-Token 头。鉴权列说明：公开=无需登录；会话=任意登录角色；editor=编辑及以上；admin=管理员。" },
{ tbl: { head: ["功能", "Method", "URL", "鉴权"], w: [40, 12, 34, 14], rows: [
  ["健康检查", "GET", "/api/health", "公开"],
  ["初始化管理员", "POST", "/api/auth/init", "仅 users 为空"],
  ["登录", "POST", "/api/auth/login", "公开（限流）"],
  ["当前用户/CSRF", "GET", "/api/auth/me", "会话"],
  ["登出", "POST", "/api/auth/logout", "会话"],
  ["任务列表/新建", "GET/POST", "/api/tasks", "会话/editor"],
  ["任务详情/改/删", "GET/PUT/DELETE", "/api/tasks/{id}", "会话/editor"],
  ["供给列表/新增", "GET/POST", "/api/tasks/{id}/supplies", "会话/editor"],
  ["供给 CSV 导入", "POST", "/api/tasks/{id}/supplies/import", "editor"],
  ["供给修改/删除", "PUT/DELETE", "/api/tasks/{id}/supplies/{sid}", "editor"],
  ["运行引擎（同步/异步）", "POST", "/api/tasks/{id}/runs[?async=1]", "editor"],
  ["任务运行列表", "GET", "/api/tasks/{id}/runs", "会话"],
  ["异步作业状态", "GET", "/api/runs/jobs/{job_id}", "会话"],
  ["运行结果", "GET", "/api/runs/{run_id}", "会话"],
  ["决策护照下载", "GET", "/api/tasks/{id}/passport", "会话"],
  ["选定方案/列表", "POST/GET", "/api/tasks/{id}/selections", "editor/会话"],
  ["证据任务列表/创建", "GET/POST", "/api/tasks/{id}/evidence-tasks", "会话/editor"],
  ["证据任务更新", "PUT", "/api/tasks/{id}/evidence-tasks/{n}", "editor"],
  ["证据版本列表/提交", "GET/POST", "/api/tasks/{id}/evidence-versions", "会话/editor"],
  ["确认采购", "POST", "/api/tasks/{id}/confirm", "editor"],
  ["反馈列表/录入", "GET/POST", "/api/tasks/{id}/feedback", "会话/editor"],
  ["预留创建/列表", "POST/GET", "/api/tasks/{id}/reservations", "editor/会话"],
  ["预留状态流转", "POST", "/api/reservations/{n}/{confirm|release|cancel}", "editor"],
  ["批次实时可用量", "GET", "/api/batches/{id}/availability", "会话"],
  ["撮合试算", "POST", "/api/matching/preview", "editor"],
  ["撮合建议单导出", "POST", "/api/matching/sheet", "editor"],
  ["用户列表/创建", "GET/POST", "/api/users", "admin"],
  ["创建备份", "POST", "/api/backup", "admin"],
  ["备份列表", "GET", "/api/backups", "admin"],
  ["恢复备份", "POST", "/api/backups/{name}/restore", "admin"],
  ["审计查询", "GET", "/api/audit", "admin"],
]} },
{ p: "核心 API 举例——登录：谁调用=登录页；入口 server.py _api_login；操作 users/sessions 表；错误 401（凭据错）、429（限流）。curl 验证：" },
{ code: "curl -i -X POST http://127.0.0.1:8765/api/auth/login ^\n  -H \"Content-Type: application/json\" ^\n  -d \"{\\\"username\\\":\\\"admin\\\",\\\"password\\\":\\\"your_password_here\\\"}\"" },
{ p: "运行引擎：入口 _api_run_engine；先冻结输入快照（因子内容 SHA256）再调 src/material.py；写 runs 表；同步返回 run_id，异步返回 202+job_id（单作业守卫，第二个后台作业 409）。错误 400 校验失败、409 作业冲突、401/403 鉴权。" },

{ h1: "第 15 章 数据库说明" },
{ p: "SQLite 单文件，14 张表，全部由 pilot/db.py 建表与迁移（当前 schema v5）。主键均为自增 id 或自然键；表间以 batch_id/task_id/user_id 关联；写入统一走事务，预留使用原子条件更新防超卖。" },
{ tbl: { head: ["表", "用途", "关键字段/关联"], w: [22, 40, 38], rows: [
  ["users", "账号与角色", "username 唯一、password_hash、salt、role、active"],
  ["sessions", "会话", "token、user_id→users、csrf_token、expires_at"],
  ["tasks", "替代任务", "id（自然键）、case_id、demand_json、status"],
  ["supplies", "任务下供给批次", "task_id→tasks、supply_id、supply_json、batch_id→batches"],
  ["batches", "全局批次库存", "batch_id、available_mass_t（预留/确认实时扣减）"],
  ["evidence_tasks", "补证任务", "task_id、状态机 open→submitted→passed/rejected"],
  ["evidence_versions", "证据版本（不可覆盖）", "task_id、version、evidence_json"],
  ["runs", "引擎运行", "id、task_id、result_json、input_snapshot_json、config_sha256"],
  ["selections", "选定方案", "task_id、run_id、option_id"],
  ["reservations", "预留（全局批次）", "batch_id、状态（confirm/release/cancel）、原子条件更新"],
  ["feedback", "履约反馈", "task_id、真实/模拟分开"],
  ["audit_log", "审计", "user、action、before/after、时间"],
  ["relations", "外部编号三元组", "unique 约束幂等"],
  ["meta", "schema 版本等", "key/value"],
]} },

{ h1: "第 16 章 如何修改已有功能" },
{ p: "每个功能的调用链已在第 12/13 章给出。常见修改场景对应入口：" },
{ tbl: { head: ["修改场景", "需要动的文件（按顺序）"], w: [34, 66], rows: [
  ["只改页面样式", "pilot/static/style.css（深浅色令牌都在 ：root）"],
  ["改页面文案/交互", "pilot/static/app.js 对应视图函数"],
  ["改请求参数或校验", "app.js 请求体 → pilot/api.py → src/validation.py"],
  ["改业务计算逻辑", "src/material.py / ledger.py（须逐位一致验证+47 组核验）"],
  ["改返回结构", "server.py _api_* → app.js 对应渲染函数 → tests 断言"],
  ["改数据库字段", "pilot/db.py 迁移 → api.py → server.py → app.js → tests（见第 21 章）"],
  ["改权限", "server.py 路由分支的 _require 角色 → auth.py ROLE_RANK"],
  ["改因子/口径", "config/material_emission_factors.yaml（改约定=新基准版本，须显式确认）"],
]} },

{ h1: "第 17 章 修改功能的标准流程" },
{ code: "明确需求\n ↓\n在第 12 章表定位功能 → 沿第 13 章调用链读代码\n ↓\n确认数据结构（pilot/db.py 表字段）与 API（server.py 路由）\n ↓\n最小修改（红线：引擎改动须逐位一致；锚点数值不可变）\n ↓\n启动工作台实测\n ↓\npython -m pytest tests -q          # 271 项全绿\npython docs/独立核验脚本-v10.py     # 47/47\npython -m pytest tests/test_docs_wording.py -q   # 文案门禁\n ↓\n（动浏览器层）依次运行 tests/e2e_v16.py、e2e_v12.py、e2e_round2.py、e2e_v18.py\n ↓\n更新 CHANGELOG.md；新增交付文件先登记 scripts/build_release.py 白名单" },

{ h1: "第 18 章 如何新增功能" },
{ p: "以「新增一个需落库并暴露 API 的功能」为例，标准顺序：" },
{ code: "1. pilot/db.py：加迁移 vN→vN+1（幂等）建表/加列\n2. pilot/api.py：请求体 → 领域对象（复用 validation.py 校验）\n3. pilot/server.py：do_GET/do_POST 增路由分支 + _api_xxx 处理器\n   （鉴权 _require；返回一律 self._json；错误 _error）\n4. tests/：新增 pytest 用例（角色/CSRF/幂等/边界）\n5. pilot/static/app.js：新增视图或区块 + fetch 调用\n6. pilot/static/style.css：样式（用既有令牌，勿硬编码颜色）\n7. scripts/build_release.py：新文件登记白名单\n8. CHANGELOG.md 记录；跑第 17 章全链回归" },
{ p: "约束：不引入新框架与新运行依赖；接口返回结构与错误结构保持一致（{error, details}）；新增引擎能力必须确定性并补独立核验。" },
];
